In [12]:
import pandas as pd
from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.tsa.stattools import acf, pacf

pd.options.display.float_format  = '{:.2f}'.format

In [13]:
df = pd.read_csv('SPY.csv')
df.head()

         Date  Open  High   Low  Close  Adj Close   Volume
0  1993-01-29 43.97 43.97 43.75  43.94      26.30  1003200
1  1993-02-01 43.97 44.25 43.97  44.25      26.49   480500
2  1993-02-02 44.22 44.38 44.12  44.34      26.54   201300
3  1993-02-03 44.41 44.84 44.38  44.81      26.82   529400
4  1993-02-04 44.97 45.09 44.47  45.00      26.94   531500

In [14]:
residuals = df['Adj Close'].pct_change() - df['Adj Close'].pct_change().mean()
residuals = residuals.dropna()

In [18]:
acorr_ljungbox(residuals, boxpierce=True, return_df=True)

c:\program files\python36\lib\site-packages\statsmodels\stats\diagnostic.py:496: FutureWarning: The default value of lags is changing.  After 0.12, this value will become min(10, nobs//5). Directly setlags to silence this warning.
  "lags to silence this warning.", FutureWarning)

    lb_stat  lb_pvalue  bp_stat  bp_pvalue
1     55.48       0.00    55.45       0.00
2     59.21       0.00    59.18       0.00
3     59.23       0.00    59.20       0.00
4     63.36       0.00    63.33       0.00
5     66.02       0.00    65.98       0.00
6     72.70       0.00    72.66       0.00
7     76.65       0.00    76.60       0.00
8     81.57       0.00    81.51       0.00
9     84.55       0.00    84.49       0.00
10    84.80       0.00    84.74       0.00
11    86.30       0.00    86.24       0.00
12   101.54       0.00   101.44       0.00
13   101.96       0.00   101.87       0.00
14   102.14       0.00   102.05       0.00
15   115.97       0.00   115.84       0.00
16   130.43       0.00   130.27       0.00
17   130.52       0.00   130.35       0.00
18   138.34       0.00   138.15       0.00
19   141.21       0.00   141.01       0.00
20   142.98       0.00   142.78       0.00
21   146.95       0.00   146.73       0.00
22   147.38       0.00   147.16       0.00
23   147.38       0.00   147.17       0.00
24   147.40       0.00   147.18       0.00
25   147.83       0.00   147.61       0.00
26   147.84       0.00   147.62       0.00
27   150.57       0.00   150.34       0.00
28   151.22       0.00   150.98       0.00
29   151.90       0.00   151.66       0.00
30   152.75       0.00   152.50       0.00
31   153.58       0.00   153.34       0.00
32   153.74       0.00   153.49       0.00
33   153.93       0.00   153.69       0.00
34   182.34       0.00   181.95       0.00
35   183.32       0.00   182.92       0.00
36   184.76       0.00   184.35       0.00
37   186.17       0.00   185.75       0.00
38   186.20       0.00   185.78       0.00
39   192.15       0.00   191.70       0.00
40   192.16       0.00   191.70       0.00

In [10]:
# ljung-box from scratch
n = len(residuals)
c = n*(n+2)
racf = acf(residuals)[1:]
sum(map(lambda i: c*i[1]**2/(n-(i[0]+1)), enumerate(racf)))

c:\program files\python36\lib\site-packages\statsmodels\tsa\stattools.py:572: FutureWarning: fft=True will become the default in a future version of statsmodels. To suppress this warning, explicitly set fft=False.
  FutureWarning

192.15594767157393

In [17]:
# box-pierce from scratch
n = len(residuals)

racf = acf(residuals)[1:]
sum(map(lambda i: n*i**2, racf))

c:\program files\python36\lib\site-packages\statsmodels\tsa\stattools.py:572: FutureWarning: fft=True will become the default in a future version of statsmodels. To suppress this warning, explicitly set fft=False.
  FutureWarning

191.70252619845493